name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    # We are running at the root of the repo
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init

    - name: Select Workspace (Prod)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Tries to select 'prod', creates it if missing
      run: terraform workspace select prod || terraform workspace new prod

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # We set private_key_path to /dev/null because GitHub doesn't have the .pem file
      # This skips the Nginx installation but allows the server creation to succeed
      run: terraform apply -auto-approve -var="private_key_path=/dev/null"